# Generated by Django 5.0.3 on 2024-04-06 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_author_bookcategory_publisher_alter_book_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookCategory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
