# Generated by Django 5.0.4 on 2024-04-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('order_id', models.IntegerField(blank=True, default=None, null=True)),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('is_paid', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='')),
                ('total_price', models.FloatField()),
            ],
        ),
    ]
