# Generated by Django 4.0.1 on 2024-05-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Refunded', 'Refunded'), ('Cancel', 'Cancel')], default='Processing', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.FloatField()),
            ],
        ),
    ]
