# Generated by Django 4.1.13 on 2024-04-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('book', 'book'), ('cloth', 'cloth'), ('mobile', 'mobile')], max_length=50)),
                ('image', models.ImageField(upload_to='images/<django.db.models.fields.CharField>')),
            ],
        ),
    ]
