# Generated by Django 4.0.1 on 2024-05-15 17:59

from django.db import migrations, models
import productapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('book', 'book'), ('cloth', 'cloth'), ('mobile', 'mobile')], max_length=50)),
                ('image', models.ImageField(upload_to=productapp.models.upload_to)),
            ],
        ),
    ]
