# Generated by Django 5.0.3 on 2024-03-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('image', models.ImageField(upload_to='mobile_phone_images/')),
            ],
        ),
    ]
