# Generated by Django 5.0.3 on 2024-04-01 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Mono', 'Mono'), ('Card', 'Card'), ('Online Banking', 'Online Banking'), ('COD', 'COD')], max_length=255)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], max_length=255)),
                ('total_price', models.FloatField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
