# Generated by Django 5.0.3 on 2024-04-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Mono', 'Mono'), ('Card', 'Card'), ('Online Banking', 'Online Banking'), ('COD', 'COD')], default='COD', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Processing', max_length=255),
        ),
    ]
