# Generated by Django 5.0.3 on 2024-04-01 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.TextField()),
                ('shipping_method', models.CharField(choices=[('Standard', 'Standard'), ('Express', 'Express'), ('Super Express', 'Super Express')], max_length=255)),
                ('shipping_status', models.CharField(max_length=255)),
                ('estimated_delivery_date', models.DateField()),
                ('shipping_fee', models.FloatField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
