# Generated by Django 5.0.3 on 2024-04-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipping_fee',
            field=models.FloatField(default=2.99),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipping_method',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Express', 'Express'), ('Super Express', 'Super Express')], default='Standard', max_length=255),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipping_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('In transit', 'In transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Processing', max_length=255),
        ),
    ]
