# Generated by Django 5.0.3 on 2024-04-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Refunded', 'Refunded'), ('Cancel', 'Cancel')], default='Processing', max_length=50),
        ),
    ]
